# Generated by Django 2.1.1 on 2018-10-13 05:27

import datetime
from django.db import migrations, models
import ice_cream_conection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('role', models.CharField(default=ice_cream_conection.models.Role(1), max_length=100)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2018, 10, 13, 5, 27, 55, 382782))),
            ],
        ),
    ]
