# Generated by Django 2.1.1 on 2018-11-27 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_conection', '0004_auto_20181117_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='served_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 4, 11, 54, 862583)),
        ),
    ]
