# Generated by Django 2.1.1 on 2018-11-27 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_conection', '0005_auto_20181127_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='served_by_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='served_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 12, 44, 32, 120772)),
        ),
    ]
